name: Build and Deploy

on:
  push:
    branches: [release]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.SSH_HOST}}
          key: ${{secrets.SSH_KEY}}
          username: ${{secrets.SSH_USERNAME}}
          passphrase: ${{secrets.SSH_PASSPHRASE}}

          script: |
            rm -rf bakarya-admin-dashboard
            git clone --branch release https://github.com/thanhtradev/bakarya-admin-dashboard.git
            cd bakarya-admin-dashboard
            npm install
            npm run build
